### ISSUE TITLE
Pre-release documentation

### ISSUE THREAD

**Issue by droserasprout** [larnaa/cluecoins#24]
- [x] Module, class and method docstrings
- [x] Move docs markdown to `docs`
- [ ] AUTHORS in readme
- [x] Optionally: render PlantUML into PNG #31 
- [ ]  Renaming functions
